### ISSUE TITLE
adding the bot logs

### ISSUE THREAD

**Issue by JaquelineQC** [Notavone/discord-panel#15]
Hey, I was thinking that adding the console log in the website would be cool

**Comment by Notavone** [comment]
I personnaly use the console only when debugging new features and I remove it after because there's (NORMALLY) no bugs left
I know some people just like to see what's going on when opening the console but i'm not that type so i'm asking, what would you like to be logged ?

**Comment by JaquelineQC** [comment]
> I personnaly use the console only when debugging new features and I remove it after because there's (NORMALLY) no bugs left
> I know some people just like to see what's going on when opening the console but i'm not that type so i'm asking, what would you like to be logged ?

uhh like I think that you could do an option to enable the console log like when you start a bot with node index.js

**Comment by Notavone** [comment]
This project doesn't run on Node
What would you like to be logged exactly ?

**Comment by Notavone** [comment]
No response, please think about it then make an issue
