### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by l0vo** [Notavone/discord-panel#17]
Where do I put the bot token?

**Comment by l0vo** [comment]
Actually I just read the thing someone else had previously but when I put my token in at the top it just says that it is invalid.

**Comment by Notavone** [comment]
It has nothing to do with your token, it's because discord blocks your request to its API, i'm working on it
![Annotation 2020-08-04 092402](https://user-images.githubusercontent.com/26359477/89265110-499eaa80-d634-11ea-99b1-0e549c90895b.png)
