### ISSUE TITLE
UK lang

### ISSUE THREAD

**Issue by Payz123** [Notavone/discord-panel#19]
I made the Ukrainian language in the panel!

**Comment by Payz123** [comment]
[uk-lang.zip](https://github.com/Notavone/discord-panel/files/5063414/uk-lang.zip)

**Comment by Notavone** [comment]
Hi, please make a pull request
Guide :
[Fork a repo](https://docs.github.com/en/github/getting-started-with-github/fork-a-repo)
[Creating a pull request from a fork](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork)
