### ISSUE TITLE
please add portuguese Language 

### ISSUE THREAD

**Issue by nelsonrita11** [Notavone/discord-panel#29]
const locales = {
    "pt": {
        "cCode": "pt_Br",
        "language": "Português",
        "text": {
            "channelNameLabel": "Bate-papo",
            "scrollCheck": "Ativar animação de rolagem automática",
            "fileSent": "enviou alguns arquivo(s)",
            "attachmentTxt": "Anexos",
            "privateMessages": "Mensagem Privada",
            "userId": "ID do Usuário"
        },
        "buttons": {
            "clearLastMessages": "Limpar últimas mensagens",
            "editToken": "Edite o token",
            "refreshChat": "Atualizar bate-papo",
            "changeLanguage": "Mudar idioma",
            "send": "Enviar",
            "leave": "Sair do servidor",
            "invite": "Convite"
        },
        "infos": {
            "owner": "Dono",//We also use 'Proprietário'
            "members": "Membros",
            "vChannels": "Canais (Voz)",
            "tChannels": "Canais(texto)",
            "roles": "Cargos",
            "channels": "Canais",
            "emojis": "Emojis"
        },
        "headings": {
            "lastMessages": "Últimas mensagens",
            "guildName": "informação",
            "autoScroll": "Auto rolagem", //I think it's better to use the same one as English since nobody uses auto rolagem
        },
        "errors": {
            "error": "ERRO",
            "dm": "ERRO : Mensagem Privada",
            "emptyMsg": "ERRO : MESSAGEM VAZIA",
            "missingPermissions": "ERRO : PERMISSÕES EM FALTA"
        },
        "token": {
            "prompt": "Por favor, insira seu token de bot discord",
            "confirmation": "Você tem certeza ?",
            "invalid": "Nenhum token fornecido ou o token é inválido"
        },
        "messageType": {
            "serverJoin": "entrou no servidor",
            "pin": "fixou uma mensagem",
            "channelNews": "adicionou um canal de notícias remoto",
            "boost": "impulsionou o servidor"
        },
        "fileType": {
            "unknown": "Desconhecido",
            "img": "imagem",
            "doc": "documento",
            "pdf": "pdf",
            "video": "video",
            "audio": "audio"
        },
        "formatting": {
            "bold": "Negrito",
            "emphasis": "Ênfase",
            "underline": "Sublinhado",
            "strike": "Tachado", //I think it's better to use the same one as English since nobody uses auto rolagem
            "clear": "Limpar formatação" 
        }
    },
}

**Comment by Notavone** [comment]
Hello, please make a pull request
