### ISSUE TITLE
Hey, help needed

### ISSUE THREAD

**Issue by AmericanTrucker20** [Notavone/discord-panel#30]
Im trying to implement this code into my bot, I am having some problems, 1) Where do I put my token in the index.html? 2) How do I start the dashboard, I start my bot using **node index.js** 3) How can I view it? I would first like to connect to localhost:3000 and check if it runs fine. Please clear my doubts.

**Comment by Notavone** [comment]
Hello, this project does not run with node for the moment, when you open index.html for the first time on a **browser** you need to input your token, if you don't you can click on change bot token to input it

**Comment by AmericanTrucker20** [comment]
I use node.js for my bot, so I think this wont work with my bot, or will it?

**Comment by Notavone** [comment]
I don"t know, it is planned to make it compatible with node but not for the moment, sorry

**Comment by Notavone** [comment]
No update, closing this issue, feel free to reopen
