### ISSUE TITLE
Adding screenshots of the panel to the readme.

### ISSUE THREAD

**Issue by Gregor-Davies** [Notavone/discord-panel#41]
**Is your feature request related to a problem? Please describe.**
Kind of, I wish that there would be screenshots for people to see what it looks like it before they install it.
**Describe the solution you'd like**
Just a couple of screenshots in the readme.
**Describe alternatives you've considered**
Maybe add them in the repo...

**Comment by Notavone** [comment]
Excellent idea
I'll get to it as soon as possible
