### ISSUE TITLE
Delete message is not working

### ISSUE THREAD

**Issue by ririko5834** [Notavone/discord-panel#42]
When i want to delete message it didnt work
![image](https://user-images.githubusercontent.com/64729293/101603053-4743c700-39ff-11eb-8bd3-c7b0ce6c9774.png)

**Comment by Notavone** [comment]
Check your bot permissions

**Comment by ririko5834** [comment]
Bot has admin perms

**Comment by Notavone** [comment]
Weird, I'll see what I can do 😕
