### ISSUE TITLE
 The information on the side is missing like How many Channel Member Emojis then the Dm bug sometimes the member is sometimes there if he is reduced

### ISSUE THREAD

**Issue by Morows** [Notavone/discord-panel#46]
**Describe the bug**

**To Reproduce**
1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
-  OS:
-  Browser:

**Smartphone (please complete the following information):**
-  Device:
-  OS:
-  Browser:
-  Version:

**Additional context**

**Comment by Notavone** [comment]
I'm aware of this, I think this is because of the API but i'm not sure.
=> I don't know how to fix this atm
