### ISSUE TITLE
Where is the token place?

### ISSUE THREAD

**Issue by ghost** [Notavone/discord-panel#51]
**Describe the bug**

**To Reproduce**
1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
-  OS:
-  Browser:

**Smartphone (please complete the following information):**
-  Device:
-  OS:
-  Browser:
-  Version:

**Additional context**

**Comment by Notavone** [comment]
?
