### ISSUE TITLE
Wont take bot token

### ISSUE THREAD

**Issue by ghost** [Notavone/discord-panel#62]
**Describe the bug**

**To Reproduce**
i followed all the steps and i put in the discord bot token but i got the no token provided or invalid token provided error

**Expected behavior**
i expected it to login to the discord bot so i could send stuff
**Screenshots**

![Screenshot 2021-09-18 5 12 06 PM](https://user-images.githubusercontent.com/75540107/133908662-48bacf5d-b149-4a9f-83e6-ea6c83c58efc.png)

**Desktop (please complete the following information):**
-  OS:chrome os
-  Browser:chrome

**Smartphone (please complete the following information):**
-  Device:
-  OS:
-  Browser:
-  Version:

**Additional context**

**Comment by Notavone** [comment]
Please check your bot token,
you can find it here: [https://discord.com/developers/applications](https://discord.com/developers/applications)

**Comment by ghost** [comment]
> Please check your bot token,
> you can find it here: https://discord.com/developers/applications

it isnt working.

**Comment by kyllian-vssr** [comment]
Error in console like this maybe :
![image](https://user-images.githubusercontent.com/68754021/141386069-7959c92d-d505-410f-af40-c5e1155c8d0b.png)

**Comment by AksiSpirit** [comment]
> Error in console like this maybe : ![image](https://user-images.githubusercontent.com/68754021/141386069-7959c92d-d505-410f-af40-c5e1155c8d0b.png)

Got the same error yesterday. Everything worked before

**Comment by kyllian-vssr** [comment]
> > Error in console like this maybe : ![image](https://user-images.githubusercontent.com/68754021/141386069-7959c92d-d505-410f-af40-c5e1155c8d0b.png)
> 
> Got the same error yesterday. Everything worked before

Discord seems to patched external requests.
Only internals (discord domains & api) some ppl said to me.

**Comment by nsde** [comment]
Same here:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://discordapp.com/api/v7/gateway/bot. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 403.

**Comment by Notavone** [comment]
Hi, this is due to discord CORS parameters

**Comment by A1qt** [comment]
> Hi, this is due to discord CORS parameters

So how would one fix this issue?

**Comment by Notavone** [comment]
You can't, unless discord changes their cloudflare settings

**Comment by nsde** [comment]
oh
