### ISSUE TITLE
Constant updating channel when "spamming" messages

### ISSUE THREAD

**Issue by RobinSchapendonk** [Notavone/discord-panel#7]
If many messages are being sent, the channel updates every time a message is sent, which has as result the channel keeps updating forever and you can't read any message, my fix would be just to createMessage(message) (idk if works) instead updating the whole channel

**Comment by RobinSchapendonk** [comment]
Okay its really easy to fix, I'm gonna make a pull request real quick for you

**Comment by RobinSchapendonk** [comment]
There you go!

**Comment by Notavone** [comment]
Just saw your code and recent issue, as I said should be fixed in the next version, thanks
