### ISSUE TITLE
Embed reading in chat + text formatting

### ISSUE THREAD

**Issue by RobinSchapendonk** [Notavone/discord-panel#9]
Would be great if you add so we can actually read embeds (title, description, fields, footer, images, color)

- [x] Embed reading
- [x] Text formatting (from panel)
- [x] Text formatting (from discord)

**Comment by Notavone** [comment]
Good idea, i'll try to make something but this ain't a priority

**Comment by RobinSchapendonk** [comment]
(Same as text formatting / mentions, would be nice too)

**Comment by RobinSchapendonk** [comment]
For a normal image, you can just make the anchor an img tag, for inline text boxes you can use the same border etc.. you did on the mention button. For italic, bold and uderline you can use the b / i / u tag. It doesn't has priority, but the text formatting is easy to add, and it would make it look a lot better.

**Comment by Notavone** [comment]
text formatting is done

**Comment by Notavone** [comment]
![text formatting](https://user-images.githubusercontent.com/26359477/85235833-8c0b7f80-b418-11ea-8422-8228bff9272e.png)

**Comment by RobinSchapendonk** [comment]
Nice

**Comment by Notavone** [comment]
I won't be able to, unless someone finds a way to distinguish where formatting starts and ends in discord so i'll know which tags to close, if not it'll look like this :
`***Discord* message with __formatting__**` -> `<b><em>Discord<em> message with <u>formatting<u><b>`
or this :
`***Discord* message with __formatting__**` -> `</b></em>Discord</em> message with </u>formatting</u></b>`

**Comment by RobinSchapendonk** [comment]
How about you just split, then array[0] will be not, array[1] will if array[2] exists etc..

**Comment by Notavone** [comment]
I'm taking some time off but i'll try to work on it when I come back

**Comment by Notavone** [comment]
Text formatting is done
